# Generated by Django 3.2.25 on 2024-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldatainfo',
            name='save_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
